export const ACTION_STRING = {
  authLogin: "AUTH_LOGIN",
  authRegister: "AUTH_REGISTER",
  authLogout: "AUTH_LOGOUT",
  authForgot: "AUTH_FORGOT_PASSWORD",
  authReset: "AUTH_RESET_PASSWORD",
  userDetail: "USER_GET_DETAIL",
  userCheckPin: "USER_CHECK_PIN",
  userEditProfile: "USER_EDIT_PROFILE",
  userEditPhone: "USER_EDIT_PHONE",
  userEditImage: "USER_EDIT_IMAGE",
  userEditPin: "USER_EDIT_PIN",
  userEditPassword: "USER_EDIT_PASSWORD",
  userDeleteImage: "USER_DELETE_IMAGE",
  transactionHistory: "GET_TRANSACTIONS_HISTORY",
  topUp: "TOP_UP",
  pending: "_PENDING",
  rejected: "_REJECTED",
  fulfilled: "_FULFILLED",
  resetTransfer: "TRANSFER_RESET",
  transferData: "TRANSFER_DATA",
  transfer: "TRANSFER",
  getStatistic: "GET_STATISTIC",
};
